### PR TITLE
Application Backup Test fix for Namespace Mapping

### PR DESCRIPTION
**Pull request by gejain**
**What type of PR is this?**
>integration-test

**What this PR does / why we need it**:
- Added a check for backup and restore resource count
- Added a seperate test to validate restore without namespace mapping 

Custom job result -
Passed with 23.8 build -
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Geet/job/CustomTestStork/36/consoleText

`[2023-09-25T09:09:16.568Z] time="2023-09-25 09:09:16" level=info msg="resourcesBackedup: 13, resourcesRestored: 13"`

```
[2023-09-25T09:15:59.830Z] --- PASS: TestApplicationBackup (649.26s)
[2023-09-25T09:15:59.830Z]     --- PASS: TestApplicationBackup/applicationBackupRestoreWithoutNMTest (645.03s)
[2023-09-25T09:15:59.830Z] PASS
```

Failed with 23.7.0 build -
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Geet/job/CustomTestStork/37/consoleText

```
2023-09-25T12:01:22.244Z]     applicationbackup_test.go:195: 
[2023-09-25T12:01:22.244Z]         	Error Trace:	/go/src/github.com/libopenstorage/stork/test/integration_test/applicationbackup_test.go:195
[2023-09-25T12:01:22.244Z]         	            				/go/src/github.com/libopenstorage/stork/test/integration_test/applicationbackup_test.go:521
[2023-09-25T12:01:22.244Z]         	Error:      	Not equal: 
[2023-09-25T12:01:22.244Z]         	            	expected: 13
[2023-09-25T12:01:22.244Z]         	            	actual  : 0
[2023-09-25T12:01:22.244Z]         	Test:       	TestApplicationBackup/applicationBackupRestoreWithoutNMTest
[2023-09-25T12:01:22.244Z]         	Messages:   	Restore unsuccessful as backup resources are 13 and restore resources are 0
```

### CODE REVIEW

**Review by pp511 — COMMENTED** [review]
I see you have only shared the result of applicationBackupRestoreWithoutNMTest test. Can you also share the result of applicationBackupRestore test here with your changes. 
Also I see that in the latest Jenkins report it seems to be passing already. Why?

**Comment by gejain** [comment]
> I see you have only shared the result of applicationBackupRestoreWithoutNMTest test. Can you also share the result of applicationBackupRestore test here with your changes. Also I see that in the latest Jenkins report it seems to be passing already. Why?

Existing one with latest image having all test with namespace mapping and hence it passing, I will run existing test with my changes and put result here. Thanks!

**Review by pp511 — APPROVED** [review]
LGTM. Make sure to post result here before merging just for sanity check. Thanks.

**Comment by gejain** [comment]
> LGTM. Make sure to post result here before merging just for sanity check. Thanks.

Yeah I will do it. Thanks!

**Comment by gejain** [comment]
> LGTM. Make sure to post result here before merging just for sanity check. Thanks.

@pp511 - Please find new run -
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Geet/job/CustomTestStork/48/consoleFull
11:46:32  --- PASS: TestApplicationBackup (1244.23s)
11:46:32      --- PASS: TestApplicationBackup/applicationBackupRestoreTest (685.94s)
11:46:32      --- PASS: TestApplicationBackup/applicationBackupRestoreWithoutNMTest (554.07s)
11:46:32  PASS

**Review by olavangad-px — APPROVED** [review]

**Pull request merged**
