### PR TITLE
Add security annotations to backups during auth enabled runs

### PR DESCRIPTION
**Pull request by Rohit-PX**
Signed-off-by: Rohit-PX <rohit@portworx.com>

**What type of PR is this?**
integration-test

**What this PR does / why we need it**:
For auth enabled runs, when creating application backups without using torpedo APIs,
security annotations must be added.

**Does this PR change a user-facing CRD or CLI?**:
no

**Is a release note needed?**:
no

**Does this change need to be cherry-picked to a release branch?**:
2.4

### CODE REVIEW

**Comment by Rohit-PX** [comment]
Testing with private container here:  https://jenkins.portworx.co/job/Stork/view/Stork%20master%20Dashboard/job/stork-master-px-2.5-rel-security/7/console

**Comment by disrani-px** [comment]
@Rohit-PX Did the tests pass with this change?

**Comment by Rohit-PX** [comment]
> @Rohit-PX Did the tests pass with this change?

I have not run the complete DEV job yet, will do that and post the link here

**Comment by disrani-px** [comment]
@Rohit-PX Any update on this?

**Comment by Rohit-PX** [comment]
> @Rohit-PX Any update on this?

I need to rebase it with the latest changes and deploy an auth cluster to test it.

**Pull request closed without merging**
