### PR TITLE
Pod spread

### PR DESCRIPTION
**Pull request by Rohit-PX**
**What type of PR is this?**
integration-test

**What this PR does / why we need it**:
https://portworx.atlassian.net/browse/PWX-28054

**Does this PR change a user-facing CRD or CLI?**:
no

**Is a release note needed?**:
no

**Does this change need to be cherry-picked to a release branch?**:
2.12

### CODE REVIEW

**Comment by Rohit-PX** [comment]
@pp511 I tested this out on `portworx/px-operator:1.10.2-dev` and it passed.

**Comment by pp511** [comment]
@Rohit-PX To reproduce this issue, we have to use settings such that 3 nodes get equally score by Stork. You have used repl1 volume. One node will be scored higher by Stork and a Pod will get scheduled on that node. Remaining two pods might get spread equally. Did you try running with a previous operator version and the same test fails? 
I reproduced the issue with repl3 volume in which 3 nodes are scored equally and Pods end up chosing one or two of the 3 equally scored nodes.

**Comment by Rohit-PX** [comment]
@pp511 I was able to reproduce the issue in `portworx/px-operator:2.10.1` and verified it in `portworx/operator:2.10.2-dev` using this test.

**Review by pp511 — APPROVED** [review]
LGTM

**Pull request merged**
